### ISSUE TITLE
problem runing cfgfmt.linux

### ISSUE THREAD

**Issue by babakyakhchali** [modulis/cisco_prov#1]
Hi
running cfgfmt.linux on debian 8.9 returns error:
./cfgfmt.linux gk001819ba64ae.txt gk001819ba64ae
-bash: ./cfgfmt.linux: No such file or directory

**Comment by staskobzar** [comment]
Hi,
Are you sure you are running this command in the right directory?
You need to be in the directory where this file is located.

**Comment by babakyakhchali** [comment]
yes I'm sure
root@app:~/cisco_prov/sip# ./cfgfmt.linux gk0014f28dd38b.txt gk0014f28dd38b
-bash: ./cfgfmt.linux: No such file or directory
as you can see I'm running it from sip directory where the cfgfmt.linux is
in

**Comment by staskobzar** [comment]
yes, I have the same problem on Debien.
It looks like this is very old binary file that supports only very old linux kernels:

ld: i386 architecture of input file `cfgfmt.linux' is incompatible with i386:x86-64 output

Unfortunately, this is binary file from Cisco and we can not change it.
You can try to look for the newer version (if it exists).

**Comment by babakyakhchali** [comment]
I managed to run the windows version of cfgfmt using wine :)

**Comment by staskobzar** [comment]
Great! I am closing the issue.
Have a good day!

**Comment by kukabu** [comment]
Hello
You must install libc6-i386
