### ISSUE TITLE
make 7912 phones fetch new configuration

### ISSUE THREAD

**Issue by babakyakhchali** [modulis/cisco_prov#2]
Hi
Is it possible to remotely make 7912 phones request new configuration file from tftp? I'm doing this on 7941 by remote pressing the sequence settings then **#** and on 7940 using telnet..

**Comment by staskobzar** [comment]
Hi,

Yes, this is supposed to be done with DHCP server, usually option 66. I think Cisco phones has vendor specified option 150.

There are a lot of information on how to configure DHCP servers for VoIP phones provisioning via tftp.

**Comment by babakyakhchali** [comment]
yes you are right. but what if you want to do it from a php script on a web server?

**Comment by staskobzar** [comment]
I am afraid you're confusing HTTP and TFTP protocols.
For example, with PHP you can create the front-end, management interface that will create configuration files in local TFTP directory.
TFTP server will be providing access to these files to the phones.
DHCP server will provide phones with IP:port of TFTP server.
